

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../constants');


module.exports = function(Client){
	return Client.sub({
		getApplication :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/platform/applications/{appId}?responseFields={responseFields}'
		})				updateApplication :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/platform/applications/{appId}?responseFields={responseFields}'
		})		
	});
};
