

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../constants');


module.exports = function(Client){
	return Client.sub({
		getDBValue :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/platform/tenantdata/{*dbEntryQuery}?responseFields={responseFields}'
		})		,
			createDBValue :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/platform/tenantdata/{*dbEntryQuery}'
		})		,
			updateDBValue :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/platform/tenantdata/{*dbEntryQuery}'
		})		,
			deleteDBValue :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/platform/tenantdata/{*dbEntryQuery}'
		})	
	});
};
