

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../../constants');


module.exports = function(Client){
	return Client.sub({
		getOrderHandlingFee :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/settings/shipping/orderhandlingfee?responseFields={responseFields}'
		})		,
			createOrderHandlingFee :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/settings/shipping/orderhandlingfee?responseFields={responseFields}'
		})		,
			updateOrderHandlingFee :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/settings/shipping/orderhandlingfee?responseFields={responseFields}'
		})		
	});
};
