

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
		getViewEntity :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/platform/entitylists/{entityListFullName}/views/{viewName}/entities/{entityId}?responseFields={responseFields}'
		}),
		getViewEntities :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/platform/entitylists/{entityListFullName}/views/{viewName}/entities?pageSize={pageSize}&startIndex={startIndex}&filter={filter}&responseFields={responseFields}'
		}),
		getViewEntityContainer :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/platform/entitylists/{entityListFullName}/views/{viewName}/entityContainers/{entityId}?responseFields={responseFields}'
		}),
		getViewEntityContainers :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/platform/entitylists/{entityListFullName}/views/{viewName}/entityContainers?pageSize={pageSize}&startIndex={startIndex}&filter={filter}&responseFields={responseFields}'
		}),
		getEntityListView :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/platform/entitylists/{entityListFullName}/views/{viewName}?responseFields={responseFields}'
		}),
		getEntityListViews :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/platform/entitylists/{entityListFullName}/views?responseFields={responseFields}'
		})		,
			createEntityListView :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/platform/entitylists/{entityListFullName}/views/?responseFields={responseFields}'
		})		,
			updateEntityListView :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/platform/entitylists/{entityListFullName}/views/{viewName}?responseFields={responseFields}'
		})		,
			deleteEntityListView :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/platform/entitylists/{entityListFullName}/views/{viewName}'
		})	
	});
};
