

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
			authenticateApp :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+homePod}api/platform/applications/authtickets/?responseFields={responseFields}'
		})		,
			refreshAppAuthTicket :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+homePod}api/platform/applications/authtickets/refresh-ticket?responseFields={responseFields}'
		})		,
			deleteAppAuthTicket :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+homePod}api/platform/applications/authtickets/{refreshToken}'
		})	
	});
};
