

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../constants');


module.exports = function(Client){
	return Client.sub({
		getDocumentTypes :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/content/documenttypes/?pageSize={pageSize}&startIndex={startIndex}&responseFields={responseFields}'
		}),
		getDocumentType :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/content/documenttypes/{documentTypeName}?responseFields={responseFields}'
		})		,
			createDocumentType :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/content/documenttypes/?responseFields={responseFields}'
		})		,
			updateDocumentType :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/content/documenttypes/{documentTypeName}?responseFields={responseFields}'
		})		
	});
};
