

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../constants');


module.exports = function(Client){
	return Client.sub({
			createDocumentListType :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/content/documentlistTypes/?responseFields={responseFields}'
		})		,
			updateDocumentListType :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/content/documentlistTypes/{documentListTypeName}?responseFields={responseFields}'
		})		
	});
};
