

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
				applyCoupon :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/carts/{cartId}/coupons/{couponCode}?responseFields={responseFields}'
		})		,
			removeCoupons :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/carts/{cartId}/coupons'
		}),
		removeCoupon :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/carts/{cartId}/coupons/{couponcode}'
		})	
	});
};
