

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
		getMessages :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/carts/current/messages?responseFields={responseFields}'
		})					removeAllMessages :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/carts/current/messages'
		}),
		removeMessage :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/carts/current/messages/{messageId}'
		})	
	});
};
