

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../../constants');


module.exports = function(Client){
	return Client.sub({
		getDeliveryAttemptSummary :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/event/push/subscriptions/{subscriptionId}/deliveryattempts/{id}?responseFields={responseFields}'
		}),
		getDeliveryAttemptSummaries :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/event/push/subscriptions/{subscriptionId}/deliveryattempts?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
		})				
	});
};
