

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
		getShipment :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/returns/{returnId}/shipments/{shipmentId}?responseFields={responseFields}'
		})		,
			createPackageShipments :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/returns/{returnId}/shipments'
		})				deleteShipment :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/returns/{returnId}/shipments/{shipmentId}'
		})	
	});
};
