

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../../../constants');


module.exports = function(Client){
	return Client.sub({
		getOptions :Client.method({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/Options'
		}),
		getOption :Client.method({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/Options/{attributeFQN}?responseFields={responseFields}'
		}),
		addOption :Client.method({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/Options?responseFields={responseFields}'
		}),
		updateOption :Client.method({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/Options/{attributeFQN}?responseFields={responseFields}'
		}),
		deleteOption :Client.method({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/Options/{attributeFQN}'
		})	
	});
};
