

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../../../constants');


module.exports = function(Client){
	return Client.sub({
		getProductVariationLocalizedDeltaPrices :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedDeltaPrice'
		}),
		getProductVariationLocalizedDeltaPrice :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedDeltaPrice/{currencyCode}?responseFields={responseFields}'
		}),
		getProductVariation :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}?responseFields={responseFields}'
		}),
		getProductVariations :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/variations?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
		})		,
			addProductVariationLocalizedDeltaPrice :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedDeltaPrice?responseFields={responseFields}'
		})		,
			updateProductVariationLocalizedDeltaPrices :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedDeltaPrice'
		}),
		updateProductVariationLocalizedDeltaPrice :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedDeltaPrice/{currencyCode}?responseFields={responseFields}'
		}),
		updateProductVariation :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}?responseFields={responseFields}'
		}),
		updateProductVariations :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/variations?responseFields={responseFields}'
		})		,
			deleteProductVariation :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}'
		}),
		deleteProductVariationLocalizedDeltaPrice :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedDeltaPrice/{currencyCode}'
		})	
	});
};
