

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
		applyCoupon :Client.method({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/orders/{orderId}/coupons/{couponCode}?updatemode={updateMode}&version={version}&responseFields={responseFields}'
		}),
		removeCoupon :Client.method({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/orders/{orderId}/coupons/{couponcode}?updatemode={updateMode}&version={version}'
		}),
		removeCoupons :Client.method({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/orders/{orderId}/coupons?updatemode={updateMode}&version={version}'
		})	
	});
};
