

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
		getAvailableDigitalPackageFulfillmentActions :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/orders/{orderId}/digitalpackages/{digitalPackageId}/actions'
		}),
		getDigitalPackage :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/orders/{orderId}/digitalpackages/{digitalPackageId}?responseFields={responseFields}'
		})		,
			createDigitalPackage :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/orders/{orderId}/digitalpackages?responseFields={responseFields}'
		})		,
			updateDigitalPackage :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/orders/{orderId}/digitalpackages/{digitalPackageId}?responseFields={responseFields}'
		})		,
			deleteDigitalPackage :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/orders/{orderId}/digitalpackages/{digitalPackageId}'
		})	
	});
};
