

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
		getOrderNotes :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/orders/{orderId}/notes'
		}),
		getOrderNote :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/orders/{orderId}/notes/{noteId}?responseFields={responseFields}'
		})		,
			createOrderNote :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/orders/{orderId}/notes?responseFields={responseFields}'
		})		,
			updateOrderNote :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/orders/{orderId}/notes/{noteId}?responseFields={responseFields}'
		})		,
			deleteOrderNote :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/orders/{orderId}/notes/{noteId}'
		})	
	});
};
