

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
		getOrderAttributes :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/orders/{orderId}/attributes'
		})		,
			createOrderAttributes :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/orders/{orderId}/attributes'
		})		,
			updateOrderAttributes :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/orders/{orderId}/attributes?removeMissing={removeMissing}'
		})		
	});
};
