

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
		getPayments :Client.method({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/orders/{orderId}/payments/?responseFields={responseFields}'
		}),
		getAvailablePaymentActions :Client.method({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/orders/{orderId}/payments/{paymentId}/actions'
		}),
		getPayment :Client.method({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/orders/{orderId}/payments/{paymentId}?responseFields={responseFields}'
		}),
		performPaymentAction :Client.method({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/orders/{orderId}/payments/{paymentId}/actions?responseFields={responseFields}'
		}),
		createPaymentAction :Client.method({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/orders/{orderId}/payments/actions?responseFields={responseFields}'
		})	
	});
};
