

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../../../constants');


module.exports = function(Client){
	return Client.sub({
		getAttributes :Client.method({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/catalog/admin/attributedefinition/attributes/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
		}),
		getAttribute :Client.method({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}?responseFields={responseFields}'
		}),
		addAttribute :Client.method({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/catalog/admin/attributedefinition/attributes/?responseFields={responseFields}'
		}),
		updateAttribute :Client.method({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}?responseFields={responseFields}'
		}),
		deleteAttribute :Client.method({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}'
		})	
	});
};
