

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
		createAnonymousShopperAuthTicket :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/customer/authtickets/anonymousshopper'
		})		,
			createUserAuthTicket :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/customer/authtickets/?responseFields={responseFields}'
		})		,
			refreshUserAuthTicket :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/customer/authtickets/refresh?refreshToken={refreshToken}&responseFields={responseFields}'
		})		
	});
};
