

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
		getVisits :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/customer/visits/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
		}),
		getVisit :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/customer/visits/{visitId}?responseFields={responseFields}'
		})		,
			addVisit :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/customer/visits/?responseFields={responseFields}'
		})		,
			updateVisit :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/customer/visits/{visitId}?responseFields={responseFields}'
		})		
	});
};
