

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../../constants');


module.exports = function(Client){
	return Client.sub({
		getTaxableTerritories :Client.method({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/settings/general/taxableterritories'
		}),
		addTaxableTerritory :Client.method({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/settings/general/taxableterritories?responseFields={responseFields}'
		}),
		updateTaxableTerritories :Client.method({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/settings/general/taxableterritories'
		})	
	});
};
