

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../constants');


module.exports = function(Client){
	return Client.sub({
		getCart :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/carts/{cartId}?responseFields={responseFields}'
		}),
		getOrCreateCart :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/carts/current?responseFields={responseFields}'
		}),
		getCartSummary :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/carts/summary?responseFields={responseFields}'
		}),
		getUserCartSummary :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/carts/user/{userId}/summary?responseFields={responseFields}'
		}),
		getUserCart :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/carts/user/{userId}?responseFields={responseFields}'
		})				updateCart :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/carts/current?responseFields={responseFields}'
		})		,
			deleteCart :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/carts/{cartId}'
		}),
		deleteCurrentCart :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/carts/current'
		})	
	});
};
