

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../constants');


module.exports = function(Client){
	return Client.sub({
		getChannelGroups :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/channelgroups/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
		}),
		getChannelGroup :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/channelgroups/{code}?responseFields={responseFields}'
		})		,
			createChannelGroup :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/channelgroups/?responseFields={responseFields}'
		})		,
			updateChannelGroup :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/channelgroups/{code}?responseFields={responseFields}'
		})		,
			deleteChannelGroup :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/channelgroups/{code}'
		})	
	});
};
