

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../constants');


module.exports = function(Client){
	return Client.sub({
		getChannels :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/channels/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
		}),
		getChannel :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/channels/{code}?responseFields={responseFields}'
		})		,
			createChannel :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/channels/?responseFields={responseFields}'
		})		,
			updateChannel :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/channels/{code}?responseFields={responseFields}'
		})		,
			deleteChannel :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/channels/{code}'
		})	
	});
};
