

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../constants');


module.exports = function(Client){
	return Client.sub({
		getLocation :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/storefront/locations/{code}?responseFields={responseFields}'
		}),
		getLocationInUsageType :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/storefront/locationUsageTypes/{locationUsageType}/locations/{code}?responseFields={responseFields}'
		}),
		getLocationsInUsageType :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/storefront/locationUsageTypes/{locationUsageType}/locations?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
		}),
		getDirectShipLocation :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/storefront/locationUsageTypes/DS/location?responseFields={responseFields}'
		}),
		getInStorePickupLocation :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/storefront/locationUsageTypes/SP/locations/{code}?responseFields={responseFields}'
		}),
		getInStorePickupLocations :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/storefront/locationUsageTypes/SP/locations?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
		})				
	});
};
