

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
		getLocations :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/admin/locations/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
		}),
		getLocation :Client.makeMethod({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/admin/locations/{locationCode}?responseFields={responseFields}'
		})		,
			addLocation :Client.makeMethod({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/admin/locations/?responseFields={responseFields}'
		})		,
			updateLocation :Client.makeMethod({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/admin/locations/{locationCode}?responseFields={responseFields}'
		})		,
			deleteLocation :Client.makeMethod({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/admin/locations/{locationCode}'
		})	
	});
};
