

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../../constants');


module.exports = function(Client){
	return Client.sub({
		getThirdPartyPaymentWorkflows :Client.method({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/settings/checkout/paymentsettings/thirdpartyworkflows'
		})	
	});
};
