

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../../constants');


module.exports = function(Client){
	return Client.sub({
		getAccountCard :Client.method({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/customer/accounts/{accountId}/cards/{cardId}?responseFields={responseFields}'
		}),
		getAccountCards :Client.method({
			method: constants.verbs.GET,
			url: '{+tenantPod}api/commerce/customer/accounts/{accountId}/cards?responseFields={responseFields}'
		}),
		addAccountCard :Client.method({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/customer/accounts/{accountId}/cards?responseFields={responseFields}'
		}),
		updateAccountCard :Client.method({
			method: constants.verbs.PUT,
			url: '{+tenantPod}api/commerce/customer/accounts/{accountId}/cards/{cardId}?responseFields={responseFields}'
		}),
		deleteAccountCard :Client.method({
			method: constants.verbs.DELETE,
			url: '{+tenantPod}api/commerce/customer/accounts/{accountId}/cards/{cardId}'
		})	
	});
};
