var sub = require('../../utils/sub'),
    makeAccessor = require('../../utils/make-accessor'),
    makeMethod = require('../../utils/make-method'),
    Client = require('../../client');

module.exports = sub(Client, {
  getAllApplications: makeMethod({
    requiresDeveloperAuth: true,
    method: "GET",
    url: "{+homePod}api/platform/developer/applications/{?_*}"
  })
});
/*
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

{
  "platform.developer.applications" : {
    "getAllApplications" : {
      "template" : ""
    },
    "getApplication" : {
      "template" : "{+homePod}api/platform/developer/applications/{applicationId}",
      "shortcutParam" : "applicationId"
    },
    "getApplicationVersion" : {
      "template" : "{+homePod}api/platform/developer/applications/applicationVersions/{applicationVersionId}",
      "shortcutParam" : "applicationVersionId"
    },
    "getPackages" : {
      "template" : "{+homePod}api/platform/developer/applications/applicationVersions/{applicationVersionId}/packages",
      "shortcutParam" : "applicationVersionId"
    },
    "getPackage" : {
      "template" : "{+homePod}api/platform/developer/applications/applicationVersions/{applicationVersionId}/packages/{packageId}"
    },
    "getPackageItemsMetadata" : {
      "template" : "{+homePod}api/platform/developer/applications/applicationVersions/{applicationVersionId}/packages/{packageId}/files"
    },
    "getPackageItemMetadata" : {
      "template" : "{+homePod}api/platform/developer/applications/applicationVersions/{applicationVersionId}/packages/{packageId}/files/?itemPath={itempath}"
    },
    "getPackageFilesZip" : {
      "template" : "{+homePod}api/platform/developer/applications/applicationVersions/{applicationVersionId}/packages/{packageId}/zip"
    },
    "addPackage" : {
      "template" : "{+homePod}api/platform/developer/applications/applicationVersions/{applicationVersionId}/packages",
      "shortcutParam" : "applicationVersionId"
    },
    "changePackageFileNameOrPath" : {
      "template" : "{+homePod}api/platform/developer/applications/applicationVersions/{applicationVersionId}/packages/{packageId}/files/change-name-or-path"
    },
    "addPackageFile" : {
      "template" : "{+homePod}api/platform/developer/applications/applicationVersions/{applicationVersionId}/packages/{packageId}/files?filePath={filepath}"
    },
    "updatePackageFile" : {
      "template" : "{+homePod}api/platform/developer/applications/applicationVersions/{applicationVersionId}/packages/{packageId}/files?filePath={filepath}"
    },
    "deletePackageFile" : {
      "template" : "{+homePod}api/platform/developer/applications/applicationVersions/{applicationVersionId}/packages/{packageId}/files?filePath={filepath}"
    }
  }

}
*/
